catalog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ProductListView.as_view(), name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core import views
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^contato$', views.contact, name='contact'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),

    url(r'^login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout, {'next_page': 'index'}, name='logout'),
    url(r'registro/', views.RegisterView.as_view(), name='registro'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.core import validators
import re


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=True)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    object = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    created = models.DateTimeField('Criado em:', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})


class Product(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey(Category)
    created = models.DateTimeField('Criado em:', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

core/models.py
from django.db import models

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'name', 'email']

core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail


class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Menssagem', widget=forms.Textarea)

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nEmail: {1}\nMenssagem: {2}\n'.format(name, email, message)
        send_mail(
            'Contato do django ecommerce',
            message,
            settings.DEFAULT_FROM_EMAIL,
            ['geovanefeitosacavalcante@gmail.com', ]
        )

accounts/views.py
from django.shortcuts import render

# Create your views here.

catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.views.generic import ListView


class ProductListView(ListView):

    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 3


class CategoryView(ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product'
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug= self.kwargs['slug'])
        return context


def product(request, slug):
    context = {
        'product': Product.objects.get(slug=slug)
    }
    return render(request, 'catalog/product.html', context)

core/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy


User = get_user_model()


class IndexView(TemplateView):

    template_name = 'index.html'


class RegisterView(CreateView):

    form_class = UserCreationForm
    template_name = 'register.html'
    model = User
    success_url = reverse_lazy('index')


def contact(request):

    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True

    context = {
        'form': form,
        'success': success,
    }
    return render(request, 'contact.html', context)

catalog/templates/catalog/category.html
{% extends 'base.html' %}
{% load pagination %}
{% block title %}{{ current_category }}| {{ block.super }}{% endblock %}
{% block conteiner %}
    <div class="page-header">
        <h1>{{ current_category }}</h1>
    </div>
    <div class="row">
        {% for product in product %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                <a href="{{ product.get_absolute_url }}">
                    <img src="http://placehold.it/350x250" alt="" />
                </a>
                <div class="caption">
                    <h3>{{ product }}</h3>
                    <p>{{ product.description | linebreaks }}</p>
                    <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'base.html' %}
{% block title %}Produto | {{ block.super }}{% endblock %}
{% block conteiner %}
    <div class="page-header">
        <h1>{{ product }}</h1>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <a href="" class="thumbnail">
                <img src="http://placehold.it/350x250" alt="" />
            </a>
        </div>
        <div class="col-sm-8">
            {{ product.description | linebreaks }}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% block title %}Lista de produtos | {{ block.super }}{% endblock %}
{% block conteiner %}
    <div class="page-header">
        <h1>Produtos</h1>
    </div>
    <div class="row">
        {% for product in products %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                <a href="{{ product.get_absolute_url }}">
                    <img src="http://placehold.it/350x250" alt="" />
                </a>
                <div class="caption">
                    <h3>{{ product }}</h3>
                    <p>{{ product.description | linebreaks }}</p>
                    <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<title>{% block title  %}Django E-Commerce{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                  {% for cat in category %}
                      <li><a href="{{ cat.get_absolute_url }}">{{ cat }}</a></li>
                  {% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                  <li><a href="{% url 'logout' %}">Sair</a></li>
              {% else %}
                  <li><a href="{% url 'login' %}">Entrar</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
		{% block conteiner %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="{% url 'index' %}">Início</a></li>
			      <li><a href="{% url 'catalog:product_list' %}">Produtos</a></li>
			      <li><a href="{% url 'contact' %}">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Contatos | {{ block.super }}{% endblock %}

{% block conteiner %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
        <div class="alert alert-success">
            Menssagem envida
        </div>
    {% else %}
        <div class="alert alert-error">
            erro
        </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post">
    {% csrf_token %}
        <fieldset>
            {% for field in  form  %}
            <div class="form-group {% if field.errors %} has-error {% endif %}">
                <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label_tag }}</label>
                <div class="col-md-9">
                   {% render_field field class="form-control" %}
                   {% for error in field.errors %}
                       <span class="help-block">{{ error }}</span>
                   {% endfor %}
                </div>
            </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% block conteiner %}
    <div class="jumbotron page-header">
        <h1>Django E-Commerce</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <p><a class="btn btn-primary">Saiba mais</a></p>
    </div>
{% endblock %}

core/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}
{% block conteiner %}
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        {% for fo in form.non_field_errors %}
        <div class="alert alert-danger ">
            {{ fo }}
        </div>
        {% endfor %}
        
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <fieldset>
                <div class="form-group {% if form.username.error %}has-error{% endif %}">
                    <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                    <div class="col-md-9">
                        {% render_field form.username class="form-control" placeholder="Usuário" %}
                        {% for fo in form.error %}
                            
                        {% endfor %}

                    </div>
                </div>
                <div class="form-group">
                    <label for="{{form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                    <div class="col-md-9">
                        {% render_field form.password class="form-control" placeholder="Senha" %}
                    </div>
                </div>
                <div class="form-group {% if form.password.error %}has-error{% endif %}">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% for page in paginator.page_range %}
                    <li {% if page_obj.number == page %} class="active" {% endif %}><a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
                {% endfor %}
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

core/templates/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Register | {{ block.super }}{% endblock %}
{% block conteiner %}
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        {% for fo in form.non_field_errors %}
        <div class="alert alert-danger ">
            {{ fo }}
        </div>
        {% endfor %}
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                     <div class="form-group {% if form.username.error %}has-error{% endif %}">
                        <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                        <div class="col-md-9">
                            {% render_field field class="form-control" placeholder=field.label %}
                            {% for fo in form %}
                                <span class="help-block">{{ fo }}</span>
                            {% endfor %}
                        </div>
                     </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}